export const incompatibleFonts = [
  "Allkin",
  "Chiron GoRound TC",
  "Chiron Sung HK",
  "Chiron Hei HK",
  "Linefont",
  "Material Icons Outlined",
  "Material Icons",
  "Material Icons Round",
  "Material Icons Two Tone",
  "Material Icons Sharp",
  "Material Symbols",
  "Material Symbols Outlined",
  "Material Symbols Rounded",
  "Material Symbols Sharp",
  "Playwrite AR Guides",
  "Playwrite AT",
  "Playwrite AT Guides",
  "Playwrite AR",
  "Playwrite AU NSW",
  "Playwrite AU QLD",
  "Playwrite AU VIC",
  "Playwrite AU SA",
  "Playwrite AU TAS Guides",
  "Playwrite AU TAS",
  "Playwrite AU SA Guides",
  "Playwrite AU NSW Guides",
  "Playwrite AU QLD Guides",
  "Playwrite BE VLG Guides",
  "Playwrite CA",
  "Playwrite BE VLG",
  "Playwrite BR Guides",
  "Playwrite BR",
  "Playwrite BE WAL",
  "Playwrite BE WAL Guides",
  "Playwrite CA Guides",
  "Playwrite CU",
  "Playwrite CL",
  "Playwrite CU Guides",
  "Playwrite CO",
  "Playwrite CO Guides",
  "Playwrite CL Guides",
  "Playwrite AU VIC Guides",
  "Playwrite CZ",
  "Playwrite DE SAS Guides",
  "Playwrite CZ Guides",
  "Playwrite DE Grund Guides",
  "Playwrite DE Grund",
  "Playwrite DE LA",
  "Playwrite DE SAS",
  "Playwrite DE LA Guides",
  "Playwrite DE VA",
  "Playwrite ES",
  "Playwrite DK Loopet",
  "Playwrite DK Loopet Guides",
  "Playwrite DK Uloopet Guides",
  "Playwrite DE VA Guides",
  "Playwrite ES Deco",
  "Playwrite DK Uloopet",
  "Playwrite ES Deco Guides",
  "Playwrite ES Guides",
  "Playwrite FR Moderne",
  "Playwrite FR Trad Guides",
  "Playwrite GB J",
  "Playwrite FR Moderne Guides",
  "Playwrite FR Trad",
  "Playwrite GB J Guides",
  "Playwrite GB S",
  "Playwrite HR",
  "Playwrite GB S Guides",
  "Playwrite HR Guides",
  "Playwrite HR Lijeva",
  "Playwrite HU Guides",
  "Playwrite HU",
  "Playwrite HR Lijeva Guides",
  "Playwrite ID",
  "Playwrite ID Guides",
  "Playwrite IE",
  "Playwrite IE Guides",
  "Playwrite IN Guides",
  "Playwrite IN",
  "Playwrite IS",
  "Playwrite IT Moderna",
  "Playwrite IT Trad",
  "Playwrite IS Guides",
  "Playwrite IT Moderna Guides",
  "Playwrite IT Trad Guides",
  "Playwrite MX Guides",
  "Playwrite NG Modern Guides",
  "Playwrite NL",
  "Playwrite NL Guides",
  "Playwrite NO",
  "Playwrite NG Modern",
  "Playwrite MX",
  "Playwrite NO Guides",
  "Playwrite NZ Basic",
  "Playwrite NZ Basic Guides",
  "Playwrite PL",
  "Playwrite NZ Guides",
  "Playwrite PE",
  "Playwrite NZ",
  "Playwrite PE Guides",
  "Playwrite PL Guides",
  "Playwrite PT Guides",
  "Playwrite PT",
  "Playwrite RO",
  "Playwrite RO Guides",
  "Playwrite SK Guides",
  "Playwrite SK",
  "Playwrite TZ Guides",
  "Playwrite TZ",
  "Playwrite US Modern",
  "Playwrite US Trad Guides",
  "Playwrite VN Guides",
  "Playwrite US Modern Guides",
  "Playwrite VN",
  "Playwrite US Trad",
  "Playwrite ZA",
  "Playwrite ZA Guides",
  "Wavefont"
];